# Generated by Django 5.2.17 on 2026-09-05 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0006_ciclo_anexos_pedido'),
        ('clientes', '0005_clienteauditlog'),
        ('pedidos', '0001_initial'),
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='título do compromisso')),
                ('descricao', models.TextField(blank=True, verbose_name='pauta / descrição')),
                ('tipo', models.CharField(choices=[('alinhamento', 'Alinhamento de Chamado'), ('orcamento', 'Apresentação de Orçamento'), ('homologacao', 'Homologação e Aceite'), ('suporte_emergencial', 'Suporte Emergencial'), ('avulso', 'Reunião de Suporte Avulsa')], default='alinhamento', max_length=30, verbose_name='tipo de evento')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], db_index=True, default='agendado', max_length=20, verbose_name='status do agendamento')),
                ('data_inicio', models.DateTimeField(db_index=True, verbose_name='data e hora de início')),
                ('data_fim', models.DateTimeField(verbose_name='data e hora de término')),
                ('duracao_minutos', models.PositiveIntegerField(default=45, verbose_name='duração em minutos')),
                ('google_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID do evento no Google Calendar')),
                ('google_meet_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='link da sala Google Meet')),
                ('google_sincronizado', models.BooleanField(default=False, verbose_name='sincronizado com Google')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='motivo do cancelamento')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='ciclos.ciclo', verbose_name='ciclo técnico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clientes.cliente', verbose_name='cliente')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='organizador')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='pedidos.pedido', verbose_name='pedido/chamado')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='tarefas.tarefa', verbose_name='tarefa técnica')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'db_table': 'shm_agendamento',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LembreteAgendamento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marco', models.CharField(choices=[('24h', '24 Horas Antes'), ('30m', '30 Minutos Antes'), ('15m', '15 Minutos Antes')], max_length=10, verbose_name='marco temporal')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('ignorado', 'Ignorado / Fora da Janela'), ('cancelado', 'Cancelado'), ('falha', 'Falha no Envio')], db_index=True, default='pendente', max_length=20, verbose_name='status do lembrete')),
                ('data_prevista', models.DateTimeField(verbose_name='data e hora prevista para o disparo')),
                ('disparado_em', models.DateTimeField(blank=True, null=True, verbose_name='disparado em')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='detalhes do erro')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='schedule.agendamento', verbose_name='agendamento')),
            ],
            options={
                'verbose_name': 'lembrete de agendamento',
                'verbose_name_plural': 'lembretes de agendamento',
                'db_table': 'shm_lembrete_agendamento',
                'ordering': ['data_prevista'],
                'unique_together': {('agendamento', 'marco')},
            },
        ),
        migrations.CreateModel(
            name='ParticipanteAgendamento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('tipo', models.CharField(choices=[('organizador', 'Organizador'), ('tecnico', 'Técnico da Empresa'), ('cliente', 'Representante do Cliente'), ('convidado', 'Convidado Externo')], default='cliente', max_length=20, verbose_name='tipo de participante')),
                ('status_presenca', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='status de presença')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='schedule.agendamento', verbose_name='agendamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_agenda', to=settings.AUTH_USER_MODEL, verbose_name='usuário do sistema')),
            ],
            options={
                'verbose_name': 'participante do agendamento',
                'verbose_name_plural': 'participantes do agendamento',
                'db_table': 'shm_participante_agendamento',
                'unique_together': {('agendamento', 'email')},
            },
        ),
    ]
