# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(verbose_name='descrição do serviço')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='horas estimadas')),
                ('horas_realizadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='horas realizadas')),
                ('status', models.CharField(choices=[('prevista', 'Prevista'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='prevista', max_length=15, verbose_name='status')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='ciclos.ciclo', verbose_name='ciclo')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_executadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'db_table': 'shm_tarefa',
                'ordering': ['criado_em'],
            },
        ),
    ]
