# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=4000, verbose_name='texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ciclos.ciclo')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='tarefas.tarefa')),
                ('tarefa_convertida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_origem', to='tarefas.tarefa')),
            ],
            options={
                'db_table': 'shm_comentario',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoComentario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='comentarios_anexos/%Y/%m/', verbose_name='arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho', models.IntegerField(default=0, verbose_name='tamanho em bytes')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='comunicacao.comentario')),
            ],
            options={
                'db_table': 'shm_anexo_comentario',
            },
        ),
    ]
