# Generated by Django 5.2.17 on 2026-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_comentario_parent_reacaocomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacaocomentario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='reacaocomentario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em'),
        ),
    ]
