# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
        ('contratos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSaldo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacao', models.CharField(choices=[('consumo', 'Consumo de Ciclo'), ('transferencia_envio', 'Transferência (Envio)'), ('transferencia_recebimento', 'Transferência (Recebimento)'), ('reabastecimento', 'Reabastecimento de Horas'), ('estorno', 'Estorno / Correção')], db_index=True, max_length=30, verbose_name='tipo de operação')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantidade de horas')),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='saldo resultante')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição / justificativa')),
                ('operacao_original_id', models.UUIDField(blank=True, null=True, verbose_name='operação original estornada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_saldo', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_saldo', to='ciclos.ciclo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_saldo', to='contratos.contrato', verbose_name='contrato')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_saldo', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'histórico de saldo',
                'verbose_name_plural': 'históricos de saldo',
                'db_table': 'shm_historico_saldo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Reabastecimento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantidade')),
                ('motivo', models.TextField(verbose_name='motivo do reabastecimento')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reabastecimentos', to='contratos.contrato')),
            ],
            options={
                'db_table': 'shm_reabastecimento',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaSaldo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantidade')),
                ('motivo', models.TextField(verbose_name='motivo da transferência')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contrato_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='contratos.contrato')),
                ('contrato_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='contratos.contrato')),
            ],
            options={
                'db_table': 'shm_transferencia_saldo',
            },
        ),
    ]
