# Generated by Django 5.2.17 on 2026-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosaldo',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem'),
        ),
        migrations.AddField(
            model_name='historicosaldo',
            name='metodo_aprovacao',
            field=models.CharField(default='APP', max_length=50, verbose_name='método de aprovação'),
        ),
        migrations.AddField(
            model_name='historicosaldo',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
    ]
