# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='link de redirecionamento')),
                ('lida', models.BooleanField(db_index=True, default=False, verbose_name='lida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shm_notification',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_criado', 'Pedido Aberto'), ('orcamento_apresentado', 'Orçamento Apresentado'), ('orcamento_aprovado', 'Orçamento Aprovado'), ('orcamento_rejeitado', 'Orçamento Rejeitado'), ('execucao_iniciada', 'Execução Iniciada'), ('aceite_solicitado', 'Aceite Solicitado'), ('ciclo_aceito', 'Ciclo Aceito e Encerrado'), ('aceite_recusado', 'Aceite Recusado')], max_length=30, verbose_name='tipo de evento')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline', to='ciclos.ciclo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'shm_timeline_event',
                'ordering': ['-timestamp'],
            },
        ),
    ]
