# Generated by Django 5.2.17 on 2026-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
    ]
