# Generated by Django 5.2.17 on 2026-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_timelineevent_ip_origem_timelineevent_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='código do evento')),
                ('categoria', models.CharField(choices=[('autenticacao', 'Autenticação e Acesso'), ('clientes', 'Clientes e Usuários'), ('contratos', 'Contratos e Vigência'), ('saldo', 'Saldo e Franquia de Horas'), ('pedidos', 'Chamados e Pedidos Técnicos'), ('ciclos', 'Orçamentos, Execução e Aceites')], db_index=True, max_length=30, verbose_name='categoria')),
                ('nome', models.CharField(max_length=150, verbose_name='nome amigável')),
                ('descricao', models.TextField(verbose_name='descrição detalhada do gatilho')),
                ('ativo_email', models.BooleanField(default=True, verbose_name='enviar por e-mail')),
                ('ativo_in_app', models.BooleanField(default=True, verbose_name='gerar notificação in-app')),
                ('notificar_empresa_admin', models.BooleanField(default=True, verbose_name='notificar admins da empresa')),
                ('notificar_empresa_tecnico', models.BooleanField(default=True, verbose_name='notificar técnicos da empresa')),
                ('notificar_cliente_gerente', models.BooleanField(default=True, verbose_name='notificar gerentes do cliente')),
                ('notificar_cliente_comum', models.BooleanField(default=False, verbose_name='notificar solicitantes do cliente')),
                ('notificar_gestor_contrato', models.BooleanField(default=True, verbose_name='notificar gestor do contrato')),
                ('notificar_emails_cc', models.BooleanField(default=True, verbose_name='enviar cópia para lista CC do contrato/cliente')),
                ('emails_adicionais', models.JSONField(blank=True, default=list, verbose_name='e-mails fixos adicionais')),
                ('bloqueado_edicao', models.BooleanField(default=False, verbose_name='evento obrigatório do sistema')),
            ],
            options={
                'db_table': 'shm_configuracao_notificacao',
                'ordering': ['categoria', 'codigo'],
            },
        ),
    ]
