# Generated by Reversa for Feature 003-nao-enviar-para-autor on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_configuracaonotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='nao_enviar_autor',
            field=models.BooleanField(
                default=True,
                help_text='Quando ativo, impede o envio de e-mails para o usuário que realizou a ação disparadora.',
                verbose_name='não enviar para o autor da ação',
            ),
        ),
    ]
