# Generated by Django 5.2.17 on 2026-09-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_configuracaonotificacao_nao_enviar_autor'),
        ('schedule', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline', to='schedule.agendamento'),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='categoria',
            field=models.CharField(choices=[('autenticacao', 'Autenticação e Acesso'), ('clientes', 'Clientes e Usuários'), ('contratos', 'Contratos e Vigência'), ('saldo', 'Saldo e Franquia de Horas'), ('pedidos', 'Chamados e Pedidos Técnicos'), ('ciclos', 'Orçamentos, Execução e Aceites'), ('schedule', 'Agendamentos e Reuniões')], db_index=True, max_length=30, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='tipo',
            field=models.CharField(choices=[('pedido_criado', 'Pedido Aberto'), ('orcamento_apresentado', 'Orçamento Apresentado'), ('orcamento_aprovado', 'Orçamento Aprovado'), ('orcamento_rejeitado', 'Orçamento Rejeitado'), ('execucao_iniciada', 'Execução Iniciada'), ('aceite_solicitado', 'Aceite Solicitado'), ('ciclo_aceito', 'Ciclo Aceito e Encerrado'), ('aceite_recusado', 'Aceite Recusado'), ('agendamento_criado', 'Reunião Agendada'), ('agendamento_remarcado', 'Reunião Remarcada'), ('agendamento_cancelado', 'Reunião Cancelada')], max_length=30, verbose_name='tipo de evento'),
        ),
    ]
