# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='número do contrato')),
                ('tipo', models.CharField(choices=[('novo', 'Novo'), ('aditivo', 'Aditivo')], default='novo', max_length=10, verbose_name='tipo')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('horas_contratadas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='horas contratadas')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='saldo de horas')),
                ('horas_consumidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='horas consumidas')),
                ('data_fim_carencia', models.DateField(blank=True, null=True, verbose_name='data fim de carência')),
                ('descricao_servicos', models.TextField(blank=True, null=True, verbose_name='descrição dos serviços')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor mensal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('pendente_aceite', 'Pendente de Aceite'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('expirado', 'Expirado')], db_index=True, default='pendente_aceite', max_length=20, verbose_name='status')),
                ('data_aceite', models.DateTimeField(blank=True, null=True, verbose_name='data de aceite')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente', verbose_name='cliente')),
                ('contrato_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos', to='contratos.contrato', verbose_name='contrato de referência')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'db_table': 'shm_contrato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AceiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('data_expiracao', models.DateTimeField(verbose_name='data de expiração')),
                ('usado', models.BooleanField(default=False, verbose_name='usado')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_links', to='contratos.contrato')),
            ],
            options={
                'db_table': 'shm_aceite_link',
            },
        ),
        migrations.CreateModel(
            name='ContratoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(upload_to='contratos/%Y/%m/', verbose_name='arquivo PDF')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='contratos.contrato')),
            ],
            options={
                'db_table': 'shm_contrato_pdf',
            },
        ),
    ]
