# Generated by Django 5.2.17 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitelink',
            name='usado_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso'),
        ),
        migrations.AddField(
            model_name='aceitelink',
            name='usado_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent de uso'),
        ),
    ]
