# Generated by Django 5.2.17 on 2026-08-25 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_aceitelink_usado_ip_aceitelink_usado_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='concluído por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_faturamento',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='dia de faturamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='emails_notificacao',
            field=models.JSONField(blank=True, default=list, verbose_name='e-mails para notificação'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail do gestor'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestor_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nome do gestor responsável'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestor_telefone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='telefone do gestor'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='justificativa de cancelamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('pendente_aceite', 'Pendente de Aceite'), ('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('expirado', 'Expirado')], db_index=True, default='pendente_aceite', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('novo', 'Novo'), ('aditivo', 'Aditivo'), ('renovacao', 'Renovação')], default='novo', max_length=15, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='ContratoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criação de Contrato'), ('aceite', 'Aceite Formalizado'), ('alteracao', 'Alteração Cadastral'), ('conclusao', 'Contrato Concluído'), ('cancelamento', 'Contrato Cancelado'), ('upload_documento', 'Upload de Documento'), ('download_documento', 'Download de Documento'), ('exclusao_documento', 'Exclusão de Documento'), ('atualizacao_emails', 'Atualização de E-mails de Notificação')], max_length=40, verbose_name='tipo de evento')),
                ('descricao', models.TextField(verbose_name='descrição do evento')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='justificativa / motivo')),
                ('documento_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do documento')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data e hora')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='contratos.contrato', verbose_name='contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_contrato', to=settings.AUTH_USER_MODEL, verbose_name='usuário autor')),
            ],
            options={
                'verbose_name': 'registro de auditoria de contrato',
                'verbose_name_plural': 'registros de auditoria de contrato',
                'db_table': 'shm_contrato_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContratoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(upload_to='contratos/documentos/%Y/%m/', verbose_name='arquivo do documento')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tipo_documento', models.CharField(choices=[('proposta', 'Proposta Comercial'), ('contrato_assinado', 'Contrato Assinado'), ('aditivo', 'Termo Aditivo'), ('distrato', 'Distrato / Rescisão'), ('outro', 'Outro Documento')], default='outro', max_length=30, verbose_name='tipo de documento')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato', verbose_name='contrato')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_contrato_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento do contrato',
                'verbose_name_plural': 'documentos do contrato',
                'db_table': 'shm_contrato_documento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
