# Generated by Django 5.2.17 on 2026-08-25 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_cancelado_em_contrato_cancelado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoauditlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criacao', 'Criação de Contrato'), ('aceite', 'Aceite Formalizado'), ('alteracao', 'Alteração Cadastral'), ('conclusao', 'Contrato Concluído'), ('cancelamento', 'Contrato Cancelado'), ('upload_documento', 'Upload de Documento'), ('download_documento', 'Download de Documento'), ('exclusao_documento', 'Exclusão de Documento'), ('atualizacao_emails', 'Atualização de E-mails de Notificação'), ('convite_email', 'Convite de E-mail de Notificação'), ('confirmacao_email', 'Confirmação de E-mail de Notificação'), ('recusa_email', 'Recusa de E-mail de Notificação')], max_length=40, verbose_name='tipo de evento'),
        ),
        migrations.CreateModel(
            name='ContratoEmailNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='endereço de e-mail')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome / cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='notificações ativas')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Confirmação'), ('confirmado', 'Confirmado / Ativo'), ('recusado', 'Recusado pelo Destinatário'), ('expirado', 'Expirado')], db_index=True, default='pendente', max_length=20, verbose_name='status de confirmação')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de confirmação')),
                ('convidado_em', models.DateTimeField(auto_now_add=True, verbose_name='data do convite')),
                ('expira_em', models.DateTimeField(verbose_name='data de expiração do token')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='data de confirmação')),
                ('confirmado_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de confirmação')),
                ('confirmado_user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent de confirmação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_notificacao', to='contratos.contrato', verbose_name='contrato')),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_notificacao_enviados', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
            ],
            options={
                'verbose_name': 'e-mail de notificação de contrato',
                'verbose_name_plural': 'e-mails de notificação de contratos',
                'db_table': 'shm_contrato_email_notificacao',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'email'), name='unique_contrato_email_notificacao')],
            },
        ),
    ]
