# Generated by Django 5.2.17 on 2026-08-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contratoauditlog_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoauditlog',
            name='documento_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='hash SHA-256 do documento'),
        ),
        migrations.AddField(
            model_name='contratodocumento',
            name='algoritmo_hash',
            field=models.CharField(default='SHA-256', max_length=20, verbose_name='algoritmo de hash'),
        ),
        migrations.AddField(
            model_name='contratodocumento',
            name='hash_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='hash SHA-256'),
        ),
        migrations.AlterField(
            model_name='contratoauditlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criacao', 'Criação de Contrato'), ('aceite', 'Aceite Formalizado'), ('alteracao', 'Alteração Cadastral'), ('conclusao', 'Contrato Concluído'), ('cancelamento', 'Contrato Cancelado'), ('upload_documento', 'Upload de Documento'), ('download_documento', 'Download de Documento'), ('exclusao_documento', 'Exclusão de Documento'), ('atualizacao_emails', 'Atualização de E-mails de Notificação'), ('convite_email', 'Convite de E-mail de Notificação'), ('confirmacao_email', 'Confirmação de E-mail de Notificação'), ('recusa_email', 'Recusa de E-mail de Notificação'), ('download_relatorio', 'Download / Impressão de Relatório')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
