# Generated by Django 5.2.17 on 2026-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contratoauditlog_documento_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoauditlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criacao', 'Criação de Contrato'), ('aceite', 'Aceite Formalizado'), ('alteracao', 'Alteração Cadastral'), ('conclusao', 'Contrato Concluído'), ('cancelamento', 'Contrato Cancelado'), ('upload_documento', 'Upload de Documento'), ('download_documento', 'Download de Documento'), ('exclusao_documento', 'Exclusão de Documento'), ('atualizacao_emails', 'Atualização de E-mails de Notificação'), ('convite_email', 'Convite de E-mail de Notificação'), ('confirmacao_email', 'Confirmação de E-mail de Notificação'), ('recusa_email', 'Recusa de E-mail de Notificação'), ('download_relatorio', 'Download / Impressão de Relatório'), ('avaliacao_ciclo', 'Avaliação de Ciclo')], max_length=40, verbose_name='tipo de evento'),
        ),
    ]
