# Generated by Django 5.2.17 on 2026-09-04 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contratoauditlog_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodocumento',
            name='arquivo',
            field=models.FileField(upload_to='contratos/documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'ppt', 'pptx', 'mp3'])], verbose_name='arquivo do documento'),
        ),
    ]
