# Generated by Django 5.2.17 on 2026-09-04 21:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def apply_immutable_trigger(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE OR REPLACE FUNCTION trg_func_forensic_audit_immutable()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'A tabela shm_forensic_audit_trail é estritamente imutável (append-only). Alterações e exclusões são proibidas por governança forense.';
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS trg_forensic_audit_immutable ON shm_forensic_audit_trail;
                CREATE TRIGGER trg_forensic_audit_immutable
                BEFORE UPDATE OR DELETE ON shm_forensic_audit_trail
                FOR EACH ROW EXECUTE FUNCTION trg_func_forensic_audit_immutable();
            """)


def remove_immutable_trigger(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute("""
                DROP TRIGGER IF EXISTS trg_forensic_audit_immutable ON shm_forensic_audit_trail;
                DROP FUNCTION IF EXISTS trg_func_forensic_audit_immutable();
            """)



class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_clienteauditlog"),
        ("contratos", "0007_alter_contratodocumento_arquivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditDailySeal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data_referencia", models.DateField(db_index=True, verbose_name="data de referência")),
                ("particao", models.CharField(db_index=True, max_length=64, verbose_name="partição")),
                ("ultimo_registro_id", models.UUIDField(blank=True, null=True, verbose_name="ID do último registro")),
                ("ultima_sequencia", models.BigIntegerField(default=0, verbose_name="última sequência")),
                ("ultimo_hash", models.CharField(max_length=64, verbose_name="último hash")),
                ("total_eventos_dia", models.PositiveIntegerField(default=0, verbose_name="total de eventos do dia")),
                ("selo_digest", models.CharField(max_length=64, verbose_name="digest SHA-256 do selo")),
                ("selado_em", models.DateTimeField(auto_now_add=True, verbose_name="selado em")),
            ],
            options={
                "verbose_name": "selo diário de integridade",
                "verbose_name_plural": "selos diários de integridade",
                "db_table": "shm_audit_daily_seal",
                "ordering": ["-data_referencia", "particao"],
                "constraints": [models.UniqueConstraint(fields=("data_referencia", "particao"), name="unique_data_particao_seal")],
            },
        ),
        migrations.CreateModel(
            name="ForensicAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("particao", models.CharField(db_index=True, max_length=64, verbose_name="partição de auditoria")),
                ("sequencia", models.BigIntegerField(db_index=True, verbose_name="sequência pericial")),
                ("tipo_evento", models.CharField(db_index=True, max_length=60, verbose_name="tipo de evento")),
                ("nivel_relevancia", models.CharField(choices=[("N1", "Nível 1 - Crítico"), ("N2", "Nível 2 - Operacional"), ("N3", "Nível 3 - Informativo")], db_index=True, default="N1", max_length=10, verbose_name="nível de relevância")),
                ("descricao", models.TextField(verbose_name="descrição do evento")),
                ("justificativa", models.TextField(blank=True, null=True, verbose_name="justificativa técnica")),
                ("usuario_nome", models.CharField(blank=True, max_length=150, null=True, verbose_name="nome do operador")),
                ("usuario_email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="e-mail do operador")),
                ("usuario_role", models.CharField(blank=True, max_length=50, null=True, verbose_name="papel do operador")),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP de origem")),
                ("user_agent", models.TextField(blank=True, null=True, verbose_name="User-Agent")),
                ("dados_payload", models.JSONField(blank=True, default=dict, verbose_name="carga útil de contexto")),
                ("payload_hash", models.CharField(max_length=64, verbose_name="hash SHA-256 do payload")),
                ("previous_hash", models.CharField(db_index=True, max_length=64, verbose_name="hash SHA-256 anterior")),
                ("current_hash", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="hash SHA-256 atual")),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="data e hora UTC")),
                ("cliente", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="trilha_forense", to="clientes.cliente", verbose_name="cliente tomador")),
                ("contrato", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="trilha_forense", to="contratos.contrato", verbose_name="contrato auditado")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="auditorias_forenses", to=settings.AUTH_USER_MODEL, verbose_name="operador")),
            ],
            options={
                "verbose_name": "registro pericial de auditoria forense",
                "verbose_name_plural": "registros periciais de auditoria forense",
                "db_table": "shm_forensic_audit_trail",
                "ordering": ["particao", "sequencia"],
                "constraints": [models.UniqueConstraint(fields=("particao", "sequencia"), name="unique_particao_sequencia"), models.UniqueConstraint(fields=("particao", "current_hash"), name="unique_particao_current_hash")],
            },
        ),
        migrations.RunPython(
            apply_immutable_trigger,
            reverse_code=remove_immutable_trigger,
        ),
    ]
