# Generated by Django 5.2.17 on 2026-09-05 09:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_forensic_audit_trail_and_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forensicauditlog',
            name='dados_payload',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='carga útil de contexto'),
        ),
    ]
