# Generated by Django 5.2.17 on 2026-08-23 14:10

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('tipo_perfil', models.CharField(choices=[('ADMIN_EMPRESA', 'Administrador da Empresa'), ('GESTOR_SUPORTE', 'Gestor de Suporte'), ('TECNICO', 'Técnico Especialista'), ('GESTOR_CLIENTE', 'Gestor do Cliente'), ('USUARIO_CLIENTE', 'Usuário do Cliente')], default='USUARIO_CLIENTE', max_length=30, verbose_name='Tipo de Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cliente', models.ForeignKey(blank=True, help_text='Preenchido somente para usuários pertencentes a um cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='shm.cliente', verbose_name='Cliente Vinculado')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, verbose_name='Código do Ciclo')),
                ('titulo_contexto', models.CharField(max_length=255, verbose_name='Contexto / Título do Ciclo')),
                ('tipo_manutencao', models.CharField(choices=[('CORRETIVA', 'Manutenção Corretiva'), ('EVOLUTIVA', 'Manutenção Evolutiva / Melhoria'), ('CONSULTORIA_TREINAMENTO', 'Consultoria / Treinamento'), ('ANALISE_TECNICA', 'Análise Técnica / Investigação'), ('OUTROS', 'Outros Serviços')], default='CORRETIVA', max_length=40, verbose_name='Tipo de Manutenção')),
                ('descricao_escopo', models.TextField(verbose_name='Descrição do Escopo')),
                ('horas_estimadas_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Estimadas Total')),
                ('horas_realizadas_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Realizadas Total')),
                ('status', models.CharField(choices=[('CRIADO', 'Criado'), ('ORCADO', 'Orçado'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação do Cliente'), ('APROVADO', 'Orçamento Aprovado'), ('REJEITADO', 'Orçamento Rejeitado'), ('EM_EXECUCAO', 'Em Execução'), ('AGUARDANDO_ACEITE', 'Aguardando Aceite Final do Cliente'), ('ACEITO', 'Aceite Concedido'), ('ENCERRADO', 'Encerrado')], default='CRIADO', max_length=30, verbose_name='Status')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Orçamento Aprovado em')),
                ('aceite_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceite Final em')),
                ('motivo_rejeicao', models.TextField(blank=True, default='', verbose_name='Motivo de Rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aceite_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_aceitos', to=settings.AUTH_USER_MODEL, verbose_name='Aceite Final por')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Orçamento Aprovado por')),
            ],
            options={
                'verbose_name': 'Ciclo de Execução',
                'verbose_name_plural': 'Ciclos de Execução',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('horas_contratadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Contratadas')),
                ('horas_herdadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo herdado (+ ou -) de contrato anterior.', max_digits=10, verbose_name='Horas Herdadas')),
                ('horas_consumidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Consumidas')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('ENCERRADO', 'Encerrado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('limite_rollover_dias', models.PositiveIntegerField(default=30, help_text='Prazo padrão em dias após o término para transferir o saldo.', verbose_name='Dias Limite para Rollover')),
                ('prorrogacao_rollover_ate', models.DateField(blank=True, help_text='Data estendida manualmente pelo Administrador para permitir o rollover.', null=True, verbose_name='Prorrogação de Rollover até')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='shm.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Assunto')),
                ('descricao_geral', models.TextField(verbose_name='Descrição Geral da Solicitação')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise Técnica'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação do Cliente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='shm.cliente', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='shm.contrato', verbose_name='Contrato Vinculado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Pedido de Suporte',
                'verbose_name_plural': 'Pedidos de Suporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('COMENTARIO', 'Comentário / Mensagem'), ('MUDANCA_STATUS', 'Mudança de Status'), ('AJUSTE_HORAS', 'Ajuste de Horas'), ('APROVACAO', 'Aprovação de Orçamento'), ('REJEICAO', 'Rejeição de Orçamento'), ('SOLICITACAO_ACEITE', 'Solicitação de Aceite'), ('ACEITE', 'Aceite Final Concedido'), ('SISTEMA', 'Evento do Sistema')], default='COMENTARIO', max_length=30, verbose_name='Tipo de Evento')),
                ('conteudo', models.TextField(verbose_name='Conteúdo / Descrição')),
                ('horas_contexto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas no Contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_timeline', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='shm.ciclo', verbose_name='Ciclo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='shm.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Evento da Timeline',
                'verbose_name_plural': 'Eventos da Timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ciclo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='shm.pedido', verbose_name='Pedido de Origem'),
        ),
        migrations.CreateModel(
            name='SaldoTransferido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horas_transferidas', models.DecimalField(decimal_places=2, help_text='Valor transferido (positivo ou negativo).', max_digits=10, verbose_name='Horas Transferidas')),
                ('data_transferencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Transferência')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='shm.contrato', verbose_name='Contrato de Destino')),
                ('contrato_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to='shm.contrato', verbose_name='Contrato de Origem')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saldo_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Transferência de Saldo',
                'verbose_name_plural': 'Transferências de Saldo',
                'ordering': ['-data_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Tarefa')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Estimadas')),
                ('horas_realizadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Horas Realizadas')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='shm.ciclo', verbose_name='Ciclo')),
                ('responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['created_at'],
            },
        ),
    ]
