# Generated by Django 5.2.17 on 2026-08-24 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordlessLoginToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token de acesso')),
                ('expira_em', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('usado', models.BooleanField(db_index=True, default=False, verbose_name='usado')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_login_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'token de login sem senha',
                'verbose_name_plural': 'tokens de login sem senha',
                'db_table': 'shm_passwordless_login_token',
                'ordering': ['-criado_em'],
            },
        ),
    ]
