# Generated by Django 5.2.17 on 2026-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordlesslogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='foto de perfil / avatar'),
        ),
    ]
