# Generated by Django 5.2.17 on 2026-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPRESA_ADMIN', 'Empresa — Gerente'), ('EMPRESA_TECNICO', 'Empresa — Analista'), ('CLIENTE_GERENTE', 'Cliente — Gerente'), ('CLIENTE_ANALISTA', 'Cliente — Analista')], db_index=True, default='CLIENTE_GERENTE', max_length=20, verbose_name='perfil de acesso'),
        ),
    ]
