# Generated by Django 5.2.17 on 2026-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], db_index=True, default='PJ', max_length=2, verbose_name='tipo')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='e-mail de contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('pessoa_contato', models.CharField(blank=True, max_length=150, null=True, verbose_name='pessoa de contato')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'shm_cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
