# Generated by Django 5.2.17 on 2026-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='emails_notificacao_padrao',
            field=models.JSONField(blank=True, default=list, verbose_name='e-mails padrão de notificação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/logos/', verbose_name='logo da empresa'),
        ),
    ]
