# Generated by Django 5.2.17 on 2026-08-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_emails_notificacao_padrao_cliente_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cargo_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cargo do contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='celular / WhatsApp'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cor_primaria_hex',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='cor primária (HEX)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='inscrição municipal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_bloqueio',
            field=models.TextField(blank=True, null=True, verbose_name='motivo do bloqueio / inativação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True, verbose_name='observações internas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ramo_atividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ramo de atividade / segmento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='site_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='site / domínio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=15, verbose_name='status'),
        ),
    ]
