# Generated by Django 5.2.17 on 2026-08-26 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cargo_contato_cliente_celular_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de aprovação / aceite'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aprovado_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da aprovação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aprovado_por_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='aprovado por (e-mail)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aprovado_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='aprovado por (nome)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aprovado_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent da aprovação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='e-mail verificado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_verificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-mail verificado em'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('pendente_aprovacao', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('inativo', 'Inativo')], db_index=True, default='pendente_aprovacao', max_length=25, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ClienteAceiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('data_expiracao', models.DateTimeField(verbose_name='data de expiração')),
                ('usado', models.BooleanField(default=False, verbose_name='usado')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('usado_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso')),
                ('usado_user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent de uso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_links', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'link de aprovação/aceite de cliente',
                'verbose_name_plural': 'links de aprovação/aceite de clientes',
                'db_table': 'shm_cliente_aceite_link',
                'ordering': ['-criado_em'],
            },
        ),
    ]
