# Generated by Django 5.2.17 on 2026-08-26 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_aprovado_em_cliente_aprovado_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID do cliente')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='nome / razão social do cliente')),
                ('cliente_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ / CPF do cliente')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação de Cadastro'), ('ALTERACAO', 'Alteração Cadastral'), ('APROVACAO', 'Aprovação de Cadastro (Magic Link)'), ('EXCLUSAO', 'Exclusão Definitiva de Cliente')], db_index=True, default='EXCLUSAO', max_length=40, verbose_name='tipo de evento')),
                ('descricao', models.TextField(verbose_name='descrição do evento')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='justificativa / motivo')),
                ('usuario_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome do usuário autor')),
                ('usuario_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail do usuário autor')),
                ('usuario_role', models.CharField(blank=True, max_length=50, null=True, verbose_name='papel do usuário')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data e hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuário autor')),
            ],
            options={
                'verbose_name': 'registro de auditoria de cliente',
                'verbose_name_plural': 'registros de auditoria de clientes',
                'db_table': 'shm_cliente_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
