# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('protocolo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='protocolo')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('descricao', models.TextField(verbose_name='descrição detalhada')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_orcamento', 'Em Orçamento'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('em_execucao', 'Em Execução'), ('aguardando_aceite', 'Aguardando Aceite'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=25, verbose_name='status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='contratos.contrato', verbose_name='contrato')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'pedido de suporte',
                'verbose_name_plural': 'pedidos de suporte',
                'db_table': 'shm_pedido',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(upload_to='pedidos_anexos/%Y/%m/', verbose_name='arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho', models.IntegerField(default=0, verbose_name='tamanho em bytes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'shm_anexo_pedido',
            },
        ),
    ]
