# Generated by Django 5.2.17 on 2026-08-23 16:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('corretiva', 'Corretiva'), ('evolutiva', 'Evolutiva'), ('preventiva', 'Preventiva'), ('analise', 'Análise'), ('consultoria', 'Consultoria'), ('treinamento', 'Treinamento')], default='analise', max_length=20, verbose_name='tipo de ciclo')),
                ('contexto', models.TextField(blank=True, null=True, verbose_name='contexto / escopo')),
                ('status', models.CharField(choices=[('orcado', 'Orçado'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('em_execucao', 'Em Execução'), ('aguardando_aceite', 'Aguardando Aceite'), ('aceito', 'Aceito'), ('cancelado', 'Cancelado')], db_index=True, default='orcado', max_length=25, verbose_name='status')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='horas estimadas')),
                ('horas_realizadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='horas realizadas')),
                ('apresentado_em', models.DateTimeField(blank=True, null=True, verbose_name='apresentado em')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token Magic Link')),
                ('aceito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_aceitos', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='operador responsável')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'ciclo de atendimento',
                'verbose_name_plural': 'ciclos de atendimento',
                'db_table': 'shm_ciclo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
