# Generated by Django 5.2.17 on 2026-08-24 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='aceito_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de aceite'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='aceito_metodo',
            field=models.CharField(default='APP', max_length=20, verbose_name='método de aceite'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='aceito_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent de aceite'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='aprovado_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de aprovação'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='aprovado_metodo',
            field=models.CharField(default='APP', max_length=20, verbose_name='método de aprovação'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='aprovado_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent de aprovação'),
        ),
        migrations.CreateModel(
            name='CicloMagicLink',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_acao', models.CharField(choices=[('aprovacao_orcamento', 'Aprovação de Orçamento'), ('aceite_ciclo', 'Aceite Final de Ciclo')], db_index=True, max_length=30, verbose_name='tipo de ação')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token seguro')),
                ('expira_em', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('usado', models.BooleanField(db_index=True, default=False, verbose_name='usado')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('usado_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso')),
                ('usado_user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent de uso')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='ciclos.ciclo', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'magic link de ciclo',
                'verbose_name_plural': 'magic links de ciclos',
                'db_table': 'shm_ciclo_magic_link',
                'ordering': ['-criado_em'],
            },
        ),
    ]
