# Generated by Django 5.2.17 on 2026-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0003_avaliacaociclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaociclo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='avaliacaociclo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='ciclomagiclink',
            name='tipo_acao',
            field=models.CharField(choices=[('aprovacao_orcamento', 'Aprovação de Orçamento'), ('aceite_ciclo', 'Aceite Final de Ciclo'), ('avaliacao_ciclo', 'Avaliação de Satisfação')], db_index=True, max_length=30, verbose_name='tipo de ação'),
        ),
    ]
