# Generated by Django 5.2.17 on 2026-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0004_alter_avaliacaociclo_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='tipo',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('evolutiva', 'Evolutiva'), ('preventiva', 'Preventiva'), ('analise', 'Análise'), ('consultoria', 'Consultoria'), ('treinamento', 'Treinamento'), ('teste', 'Teste')], default='analise', max_length=20, verbose_name='tipo de ciclo'),
        ),
    ]
