# Generated by Django 5.2.17 on 2026-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0005_alter_ciclo_tipo'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='anexos_pedido',
            field=models.ManyToManyField(blank=True, db_table='shm_ciclo_anexos_pedido', related_name='ciclos_referenciados', to='pedidos.anexopedido', verbose_name='anexos do pedido referenciados'),
        ),
    ]
